// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const generateRefreshToken = `-- name: GenerateRefreshToken :one
INSERT INTO refresh_tokens (token,created_at,updated_at,user_id,expires_at,revoked_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    NOW() + INTERVAL '60 days',
    NULL
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type GenerateRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) GenerateRefreshToken(ctx context.Context, arg GenerateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, generateRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
